export type Alignment =
    | "LAWFUL_GOOD"
    | "NEUTRAL_GOOD"
    | "CHAOTIC_GOOD"
    | "LAWFUL_NEUTRAL"
    | "TRUE_NEUTRAL"
    | "CHAOTIC_NEUTRAL"
    | "LAWFUL_EVIL"
    | "NEUTRAL_EVIL"
    | "CHAOTIC_EVIL"

export type ChallengeRating =
    | "CR_0"
    | "CR_1_8"
    | "CR_1_4"
    | "CR_1_2"
    | "CR_1"
    | "CR_2"
    | "CR_3"
    | "CR_4"
    | "CR_5"
    | "CR_6"
    | "CR_7"
    | "CR_8"
    | "CR_9"
    | "CR_10"
    | "CR_11"
    | "CR_12"
    | "CR_13"
    | "CR_14"
    | "CR_15"
    | "CR_16"
    | "CR_17"
    | "CR_18"
    | "CR_19"
    | "CR_20"
    | "CR_21"
    | "CR_22"
    | "CR_23"
    | "CR_24"
    | "CR_25"
    | "CR_26"
    | "CR_27"
    | "CR_28"
    | "CR_29"
    | "CR_30";

export type CharacterClass =
    | "ARTIFICER"
    | "BARBARIAN"
    | "BARD"
    | "CLERIC"
    | "DRUID"
    | "FIGHTER"
    | "MONK"
    | "PALADIN"
    | "RANGER"
    | "ROGUE"
    | "SORCERER"
    | "WARLOCK"
    | "WIZARD";

export type CharacterRace =
    | "AASIMAR"
    | "DRAGONBORN"
    | "DWARF"
    | "ELF"
    | "GNOME"
    | "GOLIATH"
    | "HALFLING"
    | "HALF_ELF"
    | "HALF_ORC"
    | "HUMAN"
    | "ORC"
    | "TIEFLING";

export type CreatureSize =
    | "TINY"
    | "SMALL"
    | "MEDIUM"
    | "LARGE"
    | "HUGE"
    | "GARGANTUAN"

export type Difficulty =
    | "TRIVIAL"
    | "EASY"
    | "MEDIUM"
    | "HARD"
    | "DEADLY";

export type Habitat =
    | "ARCTIC"
    | "COASTAL"
    | "DESERT"
    | "FOREST"
    | "GRASSLAND"
    | "HILL"
    | "MOUNTAIN"
    | "SWAMP"
    | "UNDERDARK"
    | "UNDERWATER"
    | "URBAN";

export type MonsterType =
    | "ABERRATION"
    | "BEAST"
    | "CELESTIAL"
    | "CONSTRUCT"
    | "DRAGON"
    | "ELEMENTAL"
    | "FEY"
    | "FIEND"
    | "GIANT"
    | "HUMANOID"
    | "MONSTROSITY"
    | "OOZE"
    | "PLANT"
    | "UNDEAD";