spring.datasource.url=jdbc:postgresql://localhost:5432/dnd_screen
spring.datasource.username=dnd_user
spring.datasource.password=dnd_password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
